[package]
name = "zshleyp/poolservice"
description = "Object Pooling"
version = "0.1.0"
license = "MIT"
authors = ["zshleyp"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml", "LICENSE"]

[dependencies]
Trove = "sleitnick/trove@1.8.0"
